### ISSUE TITLE
Allow list syntax

### ISSUE THREAD

**Issue by traktuner** [williamkray/maubot-chatgpt#1]
Hello!
Thank you for this maubot - it works great!
How is the allow_users list supposed to be used?
When I add users with the real username @username:matrix.org i get a syntax error in the config file and the bot crashes:
ruamel.yaml.scanner.ScannerError: while scanning for the next token

> found character '@' that cannot start any token
>   in "<unicode string>", line 8, column 16:
>     allowed_users: @user:matrix.org
>                    ^ (line: 8)

When adding users to the list as [user1:matrix.org user2:matrix.org user3:matrix.org] it's also not working - not allowed.

Any help is appreciated - thanks!

**Comment by traktuner** [comment]
Ok, just looked at the official maubot docs.
For anybody reading that issue, the correct allowed_users syntax is:
['@user1:matrix.org' '@user2:matrix.org' '@user3:matrix.org']

**Comment by williamkray** [comment]
yes, you need to wrap the usernames in single quotes, i believe. you can also do:

```yaml
allowed_users:
- '@user1:matrix.org'
- '@user2:matrix.org'
```

etc

**Comment by brknkfr** [comment]
Is there a way to set a regex for `allowed_users`? For example like `'^@.*:domain\.tld$'`?
