### ISSUE TITLE
Not seeing a subcommand that actually calls the GPT backend, what am I missing?

### ISSUE THREAD

**Issue by scm007** [williamkray/maubot-chatgpt#3]

**Comment by williamkray** [comment]
you trigger the bot one of two ways:

- in a DM (room with just you and the bot) all messages trigger a response
- in a room with more than two people, include the bot's name to initiate a response

**Comment by scm007** [comment]
OK figured it out.

How can I have the bot know the entire history of the chat even if they are not referenced explicitly?

**Comment by williamkray** [comment]
it already does that (uses the last 10 messages in the room as context). as long as the bot is in the room, it will have these messages stored in memory and send them with the api call. knowing the entire room history is excessive and will likely yield token limit errors.
