### ISSUE TITLE
bot throws an error when not using threads if it recently joined the room

### ISSUE THREAD

**Issue by williamkray** [williamkray/maubot-chatgpt#6]
seems like the bot tries to parse the event history and breaks when it gets to the room join state event because it's not a message. workaround is to keep thread responses enabled until there are enough events in the room to push the join out of the history.

**Comment by williamkray** [comment]
Issue can be replicated when there is a recently deleted message as well

**Comment by williamkray** [comment]
trying to fix that then prompts further issues in encrypted rooms. for example, currently if there's a deleted message or the bot has just joined, the message is `Something went wrong: 'msgtype'`. however, if i wrap the logic for testing if `next_event.content['msgtype'].is_text` in a try/except block, then all following messages become `Something went wrong: Decryption error!`

i don't have the energy to debug this further. but perhaps i can enlist @MxMarx to take a look considering these are rooted in their implementation here :pray: :crossed_fingers:

**Comment by MxMarx** [comment]
I'll take a look at it!
